luzejin:
  config: kafka
  dataSource1:
    jdbcUrl: jdbc:oracle:thin:@10.71.21.151:1521:jytest
    username: riskdev
    password: riskdev_2018
    driverClassName: oracle.jdbc.OracleDriver
  dataSource2:
    jdbcUrl: jdbc:oracle:thin:@10.71.21.151:1521:jytest
    username: riskdev
    password: riskdev_2018
    driverClassName: oracle.jdbc.OracleDriver
  kafka:
    brokerAddress: 10.71.21.237:9092


spring:
  rabbitmq:
    host: 10.71.22.45
    port: 5672
    username: yhfin
    password: yhfin